dist: focal
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.7'
tinstall:
- cd ..
- pip install pytest coveralls
- git clone --depth=1 https://github.com/Nic30/hwtLib.git
- cd hwtLib
- pip install -r docs/requirements.hwt.txt
- python setup.py install
- cd ../hwtGraph
- python setup.py install
script:
- coverage run --source=hwtGraph setup.py test
deploy:
  provider: pypi
  user: nic30
  password:
    secure: Nt2Yxu3OXOE4jKdLzEEgS2LZGWYpA8u+Ohi+gz3JTZG9g2otjR4laj9wKENWuow5QqHaB42p2lj/kbDbfg3TQXM6dRm/cCN4XnAKjpTK+FmLZyEzJC4mA7ox8+yHLZyKSa48i9e8IicCDvmn3ASF/9cXww6EkrvXErGNoFIDmtxCPGat8cz+o5N6A05lXQPQHk5iP4qOUR+oKU/hoZHzXu4RdXS9q3N9o1/38Cxu9Hn5+RDBq3jcjE6/OyYeB+ujbnp75iplOif0RFjtLU1jcV7MZ9vHlZZHlHw/H51lWvo1Ql3faETpJ8TG4OFKseeqCSCuXAMYH5xPnRQp9xR7coqDQblgVM6VMUsyRc5zgUNKMxdJUnxoDlcE229jAXgH+4TQ9Ln56K0+7QUYNr2LlOlZrAouHOoLhf8FkBX/mA0SzcdKDMg55S+EraJCo3j+29CD/+y/nj7XauDbRDNx0yz+ZcZ05jEIjS6obBVbtn8W1M5x9qFuT1iDEBaHPzipnCHiUe0QsNqJXLGfGcYrsK8EBJYIPzdZi6psKwzR/1YCokZjyCzDnEv9rY5PIQuTWKiWiYjT32IFMhyRSqx8W7EGHm4WVel5YQ3ldBGzCo6jPwS9zJYgv9PwdO7PXcC8WrQaEMnHJlzBMW5j+IB0Dw3Z1aE/ir90Up/eNotZgX8=
  on:
    tags: true
    branch: master
after_success:
- coveralls
